import type { Metadata } from "next";
import "@/styles/globals.css";
import { fontSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import { Header } from "../components/header";
import { ThemeProvider } from "../components/theme-provider";
import { HeaderMini } from "../components/mini-header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn("bg-background-highlights antialiased transition-colors duration-500 ", fontSans.variable)}
            >
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                    <Header />
                    <HeaderMini />

                    <div className="relative flex flex-col">
                        <div className="flex-1">{children}</div>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
