/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useMediaQuery } from "@/lib/useMediaQuery";

export function KeyBoardHR() {
  const isMobile = useMediaQuery("(max-width: 768px)");
  const { scene } = useGLTF("/key_board.gltf");
  return (
    <>
      {isMobile ? (
        <mesh scale={[0.20, 0.20, 0.20]}>
          <primitive object={scene} rotation={[0, Math.PI / 2, Math.PI / 4]} />
        </mesh>
      ) : (
        <mesh scale={[0.35, 0.35, 0.35]}>
          <primitive object={scene} rotation={[0, Math.PI / 2, Math.PI / 4]} />
        </mesh>
      )}
    </>
  );
}

useGLTF.preload("/key_board.gltf");
